version: "3.4"

services:

  # MSSQL IMAGE
  # mssql_image:
  #   image: mcr.microsoft.com/mssql/server
  #   environment:
  #       SA_PASSWORD: "noPassword@247"
  #       ACCEPT_EULA: "Y"

  mysql_image:
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    restart: always

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:4200"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/Api/bin/
      - /app/Application/bin/
      - /app/Domain/bin/
      - /app/Infrastructure/bin/
      - /app/Persistence/bin/
      - /app/Api/obj/
      - /app/Application/obj/
      - /app/Domain/obj/
      - /app/Infrastructure/obj/
      - /app/Persistence/obj/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # For MSSQL
      # - DefaultConnection=server=mssql_image;Database=eco-appDb;user id=sa;password=noPassword@247
      # For MySQL
      - DefaultConnection=server=mysql_image;database=db;user=dbuser;password=dbuserpassword
      - AUTHORIZATION_TOKEN=ThisismenttobetheAuthorizationtoken
    depends_on:
      - mysql_image
    ports:
      - "5000:5000"